"""empty message

Revision ID: 011ab6e4c7ab
Revises: bccf9d724a11
Create Date: 2020-01-20 12:47:09.208225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011ab6e4c7ab'
down_revision = 'bccf9d724a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'blogs', ['blogId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('blogs_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blogs', ['blog_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['authorId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blogs', ['blogId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['authorId'], ['id'])
        batch_op.create_foreign_key(None, 'blogs', ['blogId'], ['id'])

    with op.batch_alter_table('blogs_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_name'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'blogs', ['blogId'], ['id'])

    # ### end Alembic commands ###
