"""add public column at blog

Revision ID: 14c40d00b613
Revises: 28be733e0bbc
Create Date: 2020-01-20 09:13:30.229272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c40d00b613'
down_revision = '28be733e0bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###
