""" make public non-nullable

Revision ID: 3e59d0fb994f
Revises: a9f878bd03c2
Create Date: 2020-01-20 11:11:16.505152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e59d0fb994f'
down_revision = 'a9f878bd03c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.CHAR(length=32),
               autoincrement=False)
        batch_op.alter_column('public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.INTEGER(),
               autoincrement=False)

    # ### end Alembic commands ###
