"""empty message

Revision ID: 89088536b98a
Revises: 0275eb5c79c0
Create Date: 2019-10-13 01:14:05.132297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89088536b98a'
down_revision = '0275eb5c79c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
