"""empty message

Revision ID: e1235894094d
Revises: 
Create Date: 2019-10-10 15:20:47.067656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1235894094d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatarUrl', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'avatarUrl')
    # ### end Alembic commands ###
